fix/arc_nonsense
CylonSB/bounded-planet pull request #72
Opened 2020-11-08 22:12 UTC by martindevans

Previously the network system handled all packets as `Arc<Packet>`. This was unnecessary for many packets (cloning is cheap), slow (Arcs are expensive) and a pain to work with (e.g. matching through Arc). Removed that, packets can _internally_ use Arc where they contain expensive to clone things (e.g. `WorldTileData` now contains an `Arc<MeshData>`).

2020-11-09 15:44 UTC, ocornoc approved these changes
It'd be nice to put in the docs of packet the caveats of `Arc`s in serde, but looks good.

2020-11-09 15:46 UTC, martindevans commented
The caveats of Serde+Arc aren't particularly relevant to packet serialisation - since a packet will never be serialised and then deserialised on the same machine it's natural to assume a copy will be made (after all: what else could happen).

2020-11-09 18:04 UTC, Jerald requested changes

2020-11-09 18:04 UTC, Jerald commented on crates/bounded_planet_core/src/bin/server/main.rs
> +            if let Packet::Pong(ref pong) = *data {
I'm pretty sure this doesn't actually need to be fancy and use the ref and stuff...? Like with the others, it should be able to have the deref removed and it should all work out.

2020-11-09 20:48 UTC, Jerald commented
My only thought on the larger direction of this is that now there is an additional concern when making new packets: the size and/or cost of cloning.

Previously you just made your packet be whatever it is you want them to be, and you didn't have to worry about accidentally slowing stuff down with large types and/or expensive clone implementations. Now, this is left up to the creator of the packet type, creating an opaque design footgun that's not obvious.

While in some ways I do see how this is "cleaner" and less stupid, I also think that it hid a lot of annoying design complexity that now needs to be addressed once again.

2020-11-09 21:18 UTC, martindevans commented
Unfortunately I think that's just something we have to deal with. Throwing an `Arc` around for _every single packet_ really wasn't a very good idea!

2020-11-09 21:20 UTC, ocornoc commented
To be clear, you profiled this, right? This is an issue with any significant impact?

2020-11-09 21:21 UTC, martindevans commented
No and probably not.

2020-11-09 21:24 UTC, Jerald commented
No matter how we cut it, packets will need to live somewhere on the heap to outlast the individual systems they're from. Whether it's an `Arc` or some internal bevy magic is irrelevant, the cost is already paid. Because of this, I think it's not going to be such a concern that `Arc`s are going to actually limit is for real.

Basically, I think the advantages outweigh the _possible_ disadvantages. As some smart computer scientist said sometime: "premature optimization is the root of all evil"

2020-11-11 19:27 UTC, Jerald requested changes

2020-11-11 19:27 UTC, Jerald commented on crates/bounded_planet_core/src/bin/client/main.rs
> +use bounded_planet::{camera::*, networking::{components::Connection, events::*, id::ConnectionId, packets::*, systems::*}};
Unroll

2020-11-11 19:27 UTC, Jerald commented on crates/bounded_planet_core/src/land/systems.rs
> +use crate::networking::{id::ConnectionId, events::SendEvent, packets::{Packet, WorldTileData, WorldTileDataRequest}};
Unroll

2020-11-11 19:27 UTC, Jerald commented on crates/bounded_planet_core/src/networking/client/plugin.rs
> +use crate::networking::{crypto::SkipServerVerification, events::{NetworkError, SendEvent}, systems::{
Unroll

2020-11-11 19:27 UTC, Jerald commented on crates/bounded_planet_core/src/networking/server/plugin.rs
> +use crate::networking::{events::{NetworkError, ReceiveEvent, SendEvent}, systems::{
Unroll

2021-11-30 13:06 UTC, closed without merging